[package]
name = "flux"
version = "0.1.5"
description = "Flux — modern API client"
authors = ["you"]
edition = "2021"

[lib]
name = "flux_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-http = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls-native-roots", "gzip", "multipart", "stream"], default-features = false }
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.31", features = ["bundled"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
thiserror = "1"
serde_yaml = "0.9"
base64 = "0.22"
sha2 = "0.10"
rand = "0.8"
urlencoding = "2"
tokio-tungstenite = { version = "0.23", features = ["rustls-tls-native-roots"] }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
axum = { version = "0.7", default-features = false, features = ["tokio", "http1"] }
http = "1"
tonic = { version = "0.12", features = ["tls", "tls-native-roots"] }
prost = "0.13"
prost-reflect = { version = "0.14", features = ["serde"] }
prost-types = "0.13"
protox = "0.7"
tonic-reflection = "0.12"
bytes = "1"
